package com.vanced.store.ui.theme.accents

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

val BlueLightThemeColors = lightColorScheme(
    primary = blue_md_theme_light_primary,
    onPrimary = blue_md_theme_light_onPrimary,
    primaryContainer = blue_md_theme_light_primaryContainer,
    onPrimaryContainer = blue_md_theme_light_onPrimaryContainer,
    secondary = blue_md_theme_light_secondary,
    onSecondary = blue_md_theme_light_onSecondary,
    secondaryContainer = blue_md_theme_light_secondaryContainer,
    onSecondaryContainer = blue_md_theme_light_onSecondaryContainer,
    tertiary = blue_md_theme_light_tertiary,
    onTertiary = blue_md_theme_light_onTertiary,
    tertiaryContainer = blue_md_theme_light_tertiaryContainer,
    onTertiaryContainer = blue_md_theme_light_onTertiaryContainer,
    error = blue_md_theme_light_error,
    errorContainer = blue_md_theme_light_errorContainer,
    onError = blue_md_theme_light_onError,
    onErrorContainer = blue_md_theme_light_onErrorContainer,
    background = blue_md_theme_light_background,
    onBackground = blue_md_theme_light_onBackground,
    surface = blue_md_theme_light_surface,
    onSurface = blue_md_theme_light_onSurface,
    surfaceVariant = blue_md_theme_light_surfaceVariant,
    onSurfaceVariant = blue_md_theme_light_onSurfaceVariant,
    outline = blue_md_theme_light_outline,
    inverseOnSurface = blue_md_theme_light_inverseOnSurface,
    inverseSurface = blue_md_theme_light_inverseSurface,
    inversePrimary = blue_md_theme_light_inversePrimary,
)

val BlueDarkThemeColors = darkColorScheme(
    primary = blue_md_theme_dark_primary,
    onPrimary = blue_md_theme_dark_onPrimary,
    primaryContainer = blue_md_theme_dark_primaryContainer,
    onPrimaryContainer = blue_md_theme_dark_onPrimaryContainer,
    secondary = blue_md_theme_dark_secondary,
    onSecondary = blue_md_theme_dark_onSecondary,
    secondaryContainer = blue_md_theme_dark_secondaryContainer,
    onSecondaryContainer = blue_md_theme_dark_onSecondaryContainer,
    tertiary = blue_md_theme_dark_tertiary,
    onTertiary = blue_md_theme_dark_onTertiary,
    tertiaryContainer = blue_md_theme_dark_tertiaryContainer,
    onTertiaryContainer = blue_md_theme_dark_onTertiaryContainer,
    error = blue_md_theme_dark_error,
    errorContainer = blue_md_theme_dark_errorContainer,
    onError = blue_md_theme_dark_onError,
    onErrorContainer = blue_md_theme_dark_onErrorContainer,
    background = blue_md_theme_dark_background,
    onBackground = blue_md_theme_dark_onBackground,
    surface = blue_md_theme_dark_surface,
    onSurface = blue_md_theme_dark_onSurface,
    surfaceVariant = blue_md_theme_dark_surfaceVariant,
    onSurfaceVariant = blue_md_theme_dark_onSurfaceVariant,
    outline = blue_md_theme_dark_outline,
    inverseOnSurface = blue_md_theme_dark_inverseOnSurface,
    inverseSurface = blue_md_theme_dark_inverseSurface,
    inversePrimary = blue_md_theme_dark_inversePrimary,
)