package com.vanced.store.ui.theme.accents

import androidx.compose.ui.graphics.Color

val blue_md_theme_light_primary = Color(0xFF00639a)
val blue_md_theme_light_onPrimary = Color(0xFFffffff)
val blue_md_theme_light_primaryContainer = Color(0xFFcbe5ff)
val blue_md_theme_light_onPrimaryContainer = Color(0xFF001d32)
val blue_md_theme_light_secondary = Color(0xFF51606f)
val blue_md_theme_light_onSecondary = Color(0xFFffffff)
val blue_md_theme_light_secondaryContainer = Color(0xFFd5e4f6)
val blue_md_theme_light_onSecondaryContainer = Color(0xFF0e1d2a)
val blue_md_theme_light_tertiary = Color(0xFF67587a)
val blue_md_theme_light_onTertiary = Color(0xFFffffff)
val blue_md_theme_light_tertiaryContainer = Color(0xFFefdbff)
val blue_md_theme_light_onTertiaryContainer = Color(0xFF221533)
val blue_md_theme_light_error = Color(0xFFba1b1b)
val blue_md_theme_light_errorContainer = Color(0xFFffdad4)
val blue_md_theme_light_onError = Color(0xFFffffff)
val blue_md_theme_light_onErrorContainer = Color(0xFF410001)
val blue_md_theme_light_background = Color(0xFFfcfcff)
val blue_md_theme_light_onBackground = Color(0xFF1a1c1e)
val blue_md_theme_light_surface = Color(0xFFfcfcff)
val blue_md_theme_light_onSurface = Color(0xFF1a1c1e)
val blue_md_theme_light_surfaceVariant = Color(0xFFdee3eb)
val blue_md_theme_light_onSurfaceVariant = Color(0xFF41474d)
val blue_md_theme_light_outline = Color(0xFF72777e)
val blue_md_theme_light_inverseOnSurface = Color(0xFFf0f0f3)
val blue_md_theme_light_inverseSurface = Color(0xFF2f3032)
val blue_md_theme_light_inversePrimary = Color(0xFF91ccff)

val blue_md_theme_dark_primary = Color(0xFF91ccff)
val blue_md_theme_dark_onPrimary = Color(0xFF003353)
val blue_md_theme_dark_primaryContainer = Color(0xFF004a75)
val blue_md_theme_dark_onPrimaryContainer = Color(0xFFcbe5ff)
val blue_md_theme_dark_secondary = Color(0xFFb8c8da)
val blue_md_theme_dark_onSecondary = Color(0xFF233240)
val blue_md_theme_dark_secondaryContainer = Color(0xFF394857)
val blue_md_theme_dark_onSecondaryContainer = Color(0xFFd5e4f6)
val blue_md_theme_dark_tertiary = Color(0xFFd2bfe6)
val blue_md_theme_dark_onTertiary = Color(0xFF382a4a)
val blue_md_theme_dark_tertiaryContainer = Color(0xFF4f4161)
val blue_md_theme_dark_onTertiaryContainer = Color(0xFFefdbff)
val blue_md_theme_dark_error = Color(0xFFffb4a9)
val blue_md_theme_dark_errorContainer = Color(0xFF930006)
val blue_md_theme_dark_onError = Color(0xFF680003)
val blue_md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val blue_md_theme_dark_background = Color(0xFF1a1c1e)
val blue_md_theme_dark_onBackground = Color(0xFFe2e2e5)
val blue_md_theme_dark_surface = Color(0xFF1a1c1e)
val blue_md_theme_dark_onSurface = Color(0xFFe2e2e5)
val blue_md_theme_dark_surfaceVariant = Color(0xFF41474d)
val blue_md_theme_dark_onSurfaceVariant = Color(0xFFc2c7ce)
val blue_md_theme_dark_outline = Color(0xFF8c9198)
val blue_md_theme_dark_inverseOnSurface = Color(0xFF1a1c1e)
val blue_md_theme_dark_inverseSurface = Color(0xFFe2e2e5)
val blue_md_theme_dark_inversePrimary = Color(0xFF00639a)