package com.vanced.store.ui.theme.accents

import androidx.compose.ui.graphics.Color

val orange_md_theme_light_primary = Color(0xFFb3282f)
val orange_md_theme_light_onPrimary = Color(0xFFffffff)
val orange_md_theme_light_primaryContainer = Color(0xFFffdad6)
val orange_md_theme_light_onPrimaryContainer = Color(0xFF410005)
val orange_md_theme_light_secondary = Color(0xFF775654)
val orange_md_theme_light_onSecondary = Color(0xFFffffff)
val orange_md_theme_light_secondaryContainer = Color(0xFFffdad7)
val orange_md_theme_light_onSecondaryContainer = Color(0xFF2d1514)
val orange_md_theme_light_tertiary = Color(0xFF735a2e)
val orange_md_theme_light_onTertiary = Color(0xFFffffff)
val orange_md_theme_light_tertiaryContainer = Color(0xFFffdea7)
val orange_md_theme_light_onTertiaryContainer = Color(0xFF281900)
val orange_md_theme_light_error = Color(0xFFba1b1b)
val orange_md_theme_light_errorContainer = Color(0xFFffdad4)
val orange_md_theme_light_onError = Color(0xFFffffff)
val orange_md_theme_light_onErrorContainer = Color(0xFF410001)
val orange_md_theme_light_background = Color(0xFFfcfcfc)
val orange_md_theme_light_onBackground = Color(0xFF201a1a)
val orange_md_theme_light_surface = Color(0xFFfcfcfc)
val orange_md_theme_light_onSurface = Color(0xFF201a1a)
val orange_md_theme_light_surfaceVariant = Color(0xFFf4dddb)
val orange_md_theme_light_onSurfaceVariant = Color(0xFF524342)
val orange_md_theme_light_outline = Color(0xFF857372)
val orange_md_theme_light_inverseOnSurface = Color(0xFFfbeeec)
val orange_md_theme_light_inverseSurface = Color(0xFF362f2e)
val orange_md_theme_light_inversePrimary = Color(0xFFffb3af)

val orange_md_theme_dark_primary = Color(0xFFffb3af)
val orange_md_theme_dark_onPrimary = Color(0xFF69000c)
val orange_md_theme_dark_primaryContainer = Color(0xFF90091a)
val orange_md_theme_dark_onPrimaryContainer = Color(0xFFffdad6)
val orange_md_theme_dark_secondary = Color(0xFFe7bdba)
val orange_md_theme_dark_onSecondary = Color(0xFF442928)
val orange_md_theme_dark_secondaryContainer = Color(0xFF5d3f3d)
val orange_md_theme_dark_onSecondaryContainer = Color(0xFFffdad7)
val orange_md_theme_dark_tertiary = Color(0xFFe3c28c)
val orange_md_theme_dark_onTertiary = Color(0xFF402d05)
val orange_md_theme_dark_tertiaryContainer = Color(0xFF594319)
val orange_md_theme_dark_onTertiaryContainer = Color(0xFFffdea7)
val orange_md_theme_dark_error = Color(0xFFffb4a9)
val orange_md_theme_dark_errorContainer = Color(0xFF930006)
val orange_md_theme_dark_onError = Color(0xFF680003)
val orange_md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val orange_md_theme_dark_background = Color(0xFF201a1a)
val orange_md_theme_dark_onBackground = Color(0xFFecdfde)
val orange_md_theme_dark_surface = Color(0xFF201a1a)
val orange_md_theme_dark_onSurface = Color(0xFFecdfde)
val orange_md_theme_dark_surfaceVariant = Color(0xFF524342)
val orange_md_theme_dark_onSurfaceVariant = Color(0xFFd8c2c0)
val orange_md_theme_dark_outline = Color(0xFFa08c8b)
val orange_md_theme_dark_inverseOnSurface = Color(0xFF201a1a)
val orange_md_theme_dark_inverseSurface = Color(0xFFecdfde)
val orange_md_theme_dark_inversePrimary = Color(0xFFb3282f)