package com.vanced.store.ui.theme.accents

import androidx.compose.ui.graphics.Color

val pink_md_theme_light_primary = Color(0xFFb51d4d)
val pink_md_theme_light_onPrimary = Color(0xFFffffff)
val pink_md_theme_light_primaryContainer = Color(0xFFffd9df)
val pink_md_theme_light_onPrimaryContainer = Color(0xFF400013)
val pink_md_theme_light_secondary = Color(0xFF75565a)
val pink_md_theme_light_onSecondary = Color(0xFFffffff)
val pink_md_theme_light_secondaryContainer = Color(0xFFffdade)
val pink_md_theme_light_onSecondaryContainer = Color(0xFF2c1519)
val pink_md_theme_light_tertiary = Color(0xFF795831)
val pink_md_theme_light_onTertiary = Color(0xFFffffff)
val pink_md_theme_light_tertiaryContainer = Color(0xFFffdcb8)
val pink_md_theme_light_onTertiaryContainer = Color(0xFF2c1700)
val pink_md_theme_light_error = Color(0xFFba1b1b)
val pink_md_theme_light_errorContainer = Color(0xFFffdad4)
val pink_md_theme_light_onError = Color(0xFFffffff)
val pink_md_theme_light_onErrorContainer = Color(0xFF410001)
val pink_md_theme_light_background = Color(0xFFfcfcfc)
val pink_md_theme_light_onBackground = Color(0xFF201a1b)
val pink_md_theme_light_surface = Color(0xFFfcfcfc)
val pink_md_theme_light_onSurface = Color(0xFF201a1b)
val pink_md_theme_light_surfaceVariant = Color(0xFFf4dddf)
val pink_md_theme_light_onSurfaceVariant = Color(0xFF524345)
val pink_md_theme_light_outline = Color(0xFF847375)
val pink_md_theme_light_inverseOnSurface = Color(0xFFfaeeee)
val pink_md_theme_light_inverseSurface = Color(0xFF362f30)
val pink_md_theme_light_inversePrimary = Color(0xFFffb1bf)

val pink_md_theme_dark_primary = Color(0xFFffb1bf)
val pink_md_theme_dark_onPrimary = Color(0xFF660024)
val pink_md_theme_dark_primaryContainer = Color(0xFF910036)
val pink_md_theme_dark_onPrimaryContainer = Color(0xFFffd9df)
val pink_md_theme_dark_secondary = Color(0xFFe5bdc2)
val pink_md_theme_dark_onSecondary = Color(0xFF43292d)
val pink_md_theme_dark_secondaryContainer = Color(0xFF5c3f43)
val pink_md_theme_dark_onSecondaryContainer = Color(0xFFffdade)
val pink_md_theme_dark_tertiary = Color(0xFFebbf90)
val pink_md_theme_dark_onTertiary = Color(0xFF452b08)
val pink_md_theme_dark_tertiaryContainer = Color(0xFF5e411c)
val pink_md_theme_dark_onTertiaryContainer = Color(0xFFffdcb8)
val pink_md_theme_dark_error = Color(0xFFffb4a9)
val pink_md_theme_dark_errorContainer = Color(0xFF930006)
val pink_md_theme_dark_onError = Color(0xFF680003)
val pink_md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val pink_md_theme_dark_background = Color(0xFF201a1b)
val pink_md_theme_dark_onBackground = Color(0xFFece0e0)
val pink_md_theme_dark_surface = Color(0xFF201a1b)
val pink_md_theme_dark_onSurface = Color(0xFFece0e0)
val pink_md_theme_dark_surfaceVariant = Color(0xFF524345)
val pink_md_theme_dark_onSurfaceVariant = Color(0xFFd6c1c3)
val pink_md_theme_dark_outline = Color(0xFF9f8c8e)
val pink_md_theme_dark_inverseOnSurface = Color(0xFF201a1b)
val pink_md_theme_dark_inverseSurface = Color(0xFFece0e0)
val pink_md_theme_dark_inversePrimary = Color(0xFFb51d4d)