package com.vanced.store.ui.theme.accents

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

val PinkLightThemeColors = lightColorScheme(
    primary = pink_md_theme_light_primary,
    onPrimary = pink_md_theme_light_onPrimary,
    primaryContainer = pink_md_theme_light_primaryContainer,
    onPrimaryContainer = pink_md_theme_light_onPrimaryContainer,
    secondary = pink_md_theme_light_secondary,
    onSecondary = pink_md_theme_light_onSecondary,
    secondaryContainer = pink_md_theme_light_secondaryContainer,
    onSecondaryContainer = pink_md_theme_light_onSecondaryContainer,
    tertiary = pink_md_theme_light_tertiary,
    onTertiary = pink_md_theme_light_onTertiary,
    tertiaryContainer = pink_md_theme_light_tertiaryContainer,
    onTertiaryContainer = pink_md_theme_light_onTertiaryContainer,
    error = pink_md_theme_light_error,
    errorContainer = pink_md_theme_light_errorContainer,
    onError = pink_md_theme_light_onError,
    onErrorContainer = pink_md_theme_light_onErrorContainer,
    background = pink_md_theme_light_background,
    onBackground = pink_md_theme_light_onBackground,
    surface = pink_md_theme_light_surface,
    onSurface = pink_md_theme_light_onSurface,
    surfaceVariant = pink_md_theme_light_surfaceVariant,
    onSurfaceVariant = pink_md_theme_light_onSurfaceVariant,
    outline = pink_md_theme_light_outline,
    inverseOnSurface = pink_md_theme_light_inverseOnSurface,
    inverseSurface = pink_md_theme_light_inverseSurface,
    inversePrimary = pink_md_theme_light_inversePrimary,
)

val PinkDarkThemeColors = darkColorScheme(
    primary = pink_md_theme_dark_primary,
    onPrimary = pink_md_theme_dark_onPrimary,
    primaryContainer = pink_md_theme_dark_primaryContainer,
    onPrimaryContainer = pink_md_theme_dark_onPrimaryContainer,
    secondary = pink_md_theme_dark_secondary,
    onSecondary = pink_md_theme_dark_onSecondary,
    secondaryContainer = pink_md_theme_dark_secondaryContainer,
    onSecondaryContainer = pink_md_theme_dark_onSecondaryContainer,
    tertiary = pink_md_theme_dark_tertiary,
    onTertiary = pink_md_theme_dark_onTertiary,
    tertiaryContainer = pink_md_theme_dark_tertiaryContainer,
    onTertiaryContainer = pink_md_theme_dark_onTertiaryContainer,
    error = pink_md_theme_dark_error,
    errorContainer = pink_md_theme_dark_errorContainer,
    onError = pink_md_theme_dark_onError,
    onErrorContainer = pink_md_theme_dark_onErrorContainer,
    background = pink_md_theme_dark_background,
    onBackground = pink_md_theme_dark_onBackground,
    surface = pink_md_theme_dark_surface,
    onSurface = pink_md_theme_dark_onSurface,
    surfaceVariant = pink_md_theme_dark_surfaceVariant,
    onSurfaceVariant = pink_md_theme_dark_onSurfaceVariant,
    outline = pink_md_theme_dark_outline,
    inverseOnSurface = pink_md_theme_dark_inverseOnSurface,
    inverseSurface = pink_md_theme_dark_inverseSurface,
    inversePrimary = pink_md_theme_dark_inversePrimary,
)