package com.vanced.store.ui.theme.accents

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

val PurpleLightThemeColors = lightColorScheme(
    primary = purple_md_theme_light_primary,
    onPrimary = purple_md_theme_light_onPrimary,
    primaryContainer = purple_md_theme_light_primaryContainer,
    onPrimaryContainer = purple_md_theme_light_onPrimaryContainer,
    secondary = purple_md_theme_light_secondary,
    onSecondary = purple_md_theme_light_onSecondary,
    secondaryContainer = purple_md_theme_light_secondaryContainer,
    onSecondaryContainer = purple_md_theme_light_onSecondaryContainer,
    tertiary = purple_md_theme_light_tertiary,
    onTertiary = purple_md_theme_light_onTertiary,
    tertiaryContainer = purple_md_theme_light_tertiaryContainer,
    onTertiaryContainer = purple_md_theme_light_onTertiaryContainer,
    error = purple_md_theme_light_error,
    errorContainer = purple_md_theme_light_errorContainer,
    onError = purple_md_theme_light_onError,
    onErrorContainer = purple_md_theme_light_onErrorContainer,
    background = purple_md_theme_light_background,
    onBackground = purple_md_theme_light_onBackground,
    surface = purple_md_theme_light_surface,
    onSurface = purple_md_theme_light_onSurface,
    surfaceVariant = purple_md_theme_light_surfaceVariant,
    onSurfaceVariant = purple_md_theme_light_onSurfaceVariant,
    outline = purple_md_theme_light_outline,
    inverseOnSurface = purple_md_theme_light_inverseOnSurface,
    inverseSurface = purple_md_theme_light_inverseSurface,
    inversePrimary = purple_md_theme_light_inversePrimary,
)

val PurpleDarkThemeColors = darkColorScheme(
    primary = purple_md_theme_dark_primary,
    onPrimary = purple_md_theme_dark_onPrimary,
    primaryContainer = purple_md_theme_dark_primaryContainer,
    onPrimaryContainer = purple_md_theme_dark_onPrimaryContainer,
    secondary = purple_md_theme_dark_secondary,
    onSecondary = purple_md_theme_dark_onSecondary,
    secondaryContainer = purple_md_theme_dark_secondaryContainer,
    onSecondaryContainer = purple_md_theme_dark_onSecondaryContainer,
    tertiary = purple_md_theme_dark_tertiary,
    onTertiary = purple_md_theme_dark_onTertiary,
    tertiaryContainer = purple_md_theme_dark_tertiaryContainer,
    onTertiaryContainer = purple_md_theme_dark_onTertiaryContainer,
    error = purple_md_theme_dark_error,
    errorContainer = purple_md_theme_dark_errorContainer,
    onError = purple_md_theme_dark_onError,
    onErrorContainer = purple_md_theme_dark_onErrorContainer,
    background = purple_md_theme_dark_background,
    onBackground = purple_md_theme_dark_onBackground,
    surface = purple_md_theme_dark_surface,
    onSurface = purple_md_theme_dark_onSurface,
    surfaceVariant = purple_md_theme_dark_surfaceVariant,
    onSurfaceVariant = purple_md_theme_dark_onSurfaceVariant,
    outline = purple_md_theme_dark_outline,
    inverseOnSurface = purple_md_theme_dark_inverseOnSurface,
    inverseSurface = purple_md_theme_dark_inverseSurface,
    inversePrimary = purple_md_theme_dark_inversePrimary,
)