package com.vanced.store.ui.theme.accents

import androidx.compose.ui.graphics.Color

val purple_md_theme_light_primary = Color(0xFF7142c0)
val purple_md_theme_light_onPrimary = Color(0xFFffffff)
val purple_md_theme_light_primaryContainer = Color(0xFFecdcff)
val purple_md_theme_light_onPrimaryContainer = Color(0xFF250059)
val purple_md_theme_light_secondary = Color(0xFF635a70)
val purple_md_theme_light_onSecondary = Color(0xFFffffff)
val purple_md_theme_light_secondaryContainer = Color(0xFFeadef7)
val purple_md_theme_light_onSecondaryContainer = Color(0xFF1f182b)
val purple_md_theme_light_tertiary = Color(0xFF7f525d)
val purple_md_theme_light_onTertiary = Color(0xFFffffff)
val purple_md_theme_light_tertiaryContainer = Color(0xFFffd9e2)
val purple_md_theme_light_onTertiaryContainer = Color(0xFF32101b)
val purple_md_theme_light_error = Color(0xFFba1b1b)
val purple_md_theme_light_errorContainer = Color(0xFFffdad4)
val purple_md_theme_light_onError = Color(0xFFffffff)
val purple_md_theme_light_onErrorContainer = Color(0xFF410001)
val purple_md_theme_light_background = Color(0xFFfffbfc)
val purple_md_theme_light_onBackground = Color(0xFF1d1b1f)
val purple_md_theme_light_surface = Color(0xFFfffbfc)
val purple_md_theme_light_onSurface = Color(0xFF1d1b1f)
val purple_md_theme_light_surfaceVariant = Color(0xFFe7e0eb)
val purple_md_theme_light_onSurfaceVariant = Color(0xFF49454e)
val purple_md_theme_light_outline = Color(0xFF7a757e)
val purple_md_theme_light_inverseOnSurface = Color(0xFFf5eff4)
val purple_md_theme_light_inverseSurface = Color(0xFF323033)
val purple_md_theme_light_inversePrimary = Color(0xFFd5baff)

val purple_md_theme_dark_primary = Color(0xFFd5baff)
val purple_md_theme_dark_onPrimary = Color(0xFF3f008d)
val purple_md_theme_dark_primaryContainer = Color(0xFF5826a6)
val purple_md_theme_dark_onPrimaryContainer = Color(0xFFecdcff)
val purple_md_theme_dark_secondary = Color(0xFFcdc2db)
val purple_md_theme_dark_onSecondary = Color(0xFF342d40)
val purple_md_theme_dark_secondaryContainer = Color(0xFF4b4358)
val purple_md_theme_dark_onSecondaryContainer = Color(0xFFeadef7)
val purple_md_theme_dark_tertiary = Color(0xFFf1b7c4)
val purple_md_theme_dark_onTertiary = Color(0xFF4a252f)
val purple_md_theme_dark_tertiaryContainer = Color(0xFF643a45)
val purple_md_theme_dark_onTertiaryContainer = Color(0xFFffd9e2)
val purple_md_theme_dark_error = Color(0xFFffb4a9)
val purple_md_theme_dark_errorContainer = Color(0xFF930006)
val purple_md_theme_dark_onError = Color(0xFF680003)
val purple_md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val purple_md_theme_dark_background = Color(0xFF1d1b1f)
val purple_md_theme_dark_onBackground = Color(0xFFe7e1e6)
val purple_md_theme_dark_surface = Color(0xFF1d1b1f)
val purple_md_theme_dark_onSurface = Color(0xFFe7e1e6)
val purple_md_theme_dark_surfaceVariant = Color(0xFF49454e)
val purple_md_theme_dark_onSurfaceVariant = Color(0xFFcbc4cf)
val purple_md_theme_dark_outline = Color(0xFF948e99)
val purple_md_theme_dark_inverseOnSurface = Color(0xFF1d1b1f)
val purple_md_theme_dark_inverseSurface = Color(0xFFe7e1e6)
val purple_md_theme_dark_inversePrimary = Color(0xFF7142c0)